name: ✔Build Status Check

env:
  NET_SDK_VERSION: 6.0.300

on:
  workflow_dispatch:
    paths-ignore:
      - ".github/**"
      - "Documentation/**"
      - '.editorconfig'
      - '*.runsettings'
      - '.gitattributes'
      - '.gitignore'
      - '*.md'
      - '*.yml'
      - '.vscode/**'
      - '*.sln'


jobs:
  determine_build_config:
    name: Determine Build Configuration
    runs-on: ubuntu-latest
    outputs:
      build-config: ${{ steps.get-build-config.outputs.build-config }}
    steps:
      - name: Get Build Config
        id: get-build-config
        shell: pwsh
        run: |
          # If the destination branch that the pull request is merging into is the master, do a release build
          if ( "${{ github.base_ref }}" -eq "master") {
            Write-Host "::set-output name=build-config::Release";
          } else { # Any other branch than master, do a debug build
            Write-Host "::set-output name=build-config::Debug";
          }

  get_sdk_version:
    name: Get SDK Version
    runs-on: ubuntu-latest
    outputs:
      sdk-version: ${{ steps.get-sdk-version.outputs.sdk-version }}
    steps:
      - name: Get SDK Version From Environment Variable
        id: get-sdk-version
        shell: pwsh
        run: Write-Host "::set-output name=sdk-version::${{ env.NET_SDK_VERSION }}";

  # Build Main Projects
  build_[TODO: add project name here]:
    name: Build [TODO: add project name here] Project
    needs: [determine_build_config, get_sdk_version]
    uses: KinsonDigital/Infrastructure/.github/workflows/build-status-check.yml@master
    with:
      project-name: "[TODO: add project name here]"
      build-config: ${{ needs.determine_build_config.outputs.build-config }}
      net-sdk-version: ${{ needs.get_sdk_version.outputs.sdk-version }}

  build_[TODO: add project name here]_tests:
    name: Build [TODO: add project name here] Tests Project
    needs: [determine_build_config, get_sdk_version]
    uses: KinsonDigital/Infrastructure/.github/workflows/build-status-check.yml@master
    with:
      project-name: "[TODO: add project name here]Tests"
      build-config: ${{ needs.determine_build_config.outputs.build-config }}
      net-sdk-version: ${{ needs.get_sdk_version.outputs.sdk-version }}
